version: '3'

services:
  backend:
    # image: backend_backend
    # image: takuonline:google_lense_clone_backend
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - type: bind
        source: \.     # local dir. For windows use \ instead of /
        target: /app   # docker container path
    command: >
        sh -c "python3 app.py"
    # command: >
    #     sh -c "python3 scripts/download_ml_model.py &&
    #            python3 app.py"
    # command: 'python3 scripts/download_ml_model.py &&
                # gunicorn -w 4  -b 0.0.0.0  "app:app" '
